module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '#',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LxfDRwHkBPP0s83koinr6Y?mode=wwt',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/ybxvel.jpg',
    NEWSLETTER_JID: '120363421928318889@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: ' Nediya MINI BOT 𝗩1',
    OWNER_NAME: 'Ilmin Nedisa',
    OWNER_NUMBER: '94761207139',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> Nediya Md 𝗩1',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb2l7408vd1GSo8n3a19',
};
